[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 